name: Auto PR on Push

on:
  push:
    branches-ignore:
      - main  # Ignora los push en la rama `main`

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main  # Rama base a la que se va a hacer el merge
          title: 'Auto PR: Update from push'
          body: 'This PR was automatically created from a push.'
          reviewers: ${{ github.actor }}
          branch: ${{ github.ref_name }}  # Usa la rama actual

      - name: Display PR URL
        run: echo "Pull Request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
